[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20", "pango", "pkg-config", "gobject-introspection"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && flask db upgrade && gunicorn run:app --bind 0.0.0.0:$PORT"
