import { Link } from "react-router-dom";

export default function TermsOfService() {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <Link to="/" className="legal-back">&larr; Back to Home</Link>

        <h1>Terms of Service</h1>
        <p className="legal-effective">Effective Date: March 17, 2026</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Case Raft ("the Service"), you agree to be
            bound by these Terms of Service. If you do not agree, do not use the
            Service. These terms apply to all users, including law firm
            administrators and individual attorneys.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            Case Raft is a reporting and analytics platform that integrates with
            Clio Manage via read-only API access. The Service generates case
            summary reports, firm productivity reports, revenue reports, trust
            management reports, and other analytics based on data from your Clio
            account.
          </p>
        </section>

        <section>
          <h2>3. Account Registration</h2>
          <p>
            You must sign in using your Clio Manage credentials through OAuth
            2.0. You are responsible for maintaining the security of your Clio
            account. You agree to provide accurate information and to notify us
            if you become aware of unauthorized access to your account.
          </p>
        </section>

        <section>
          <h2>4. Subscriptions and Billing</h2>
          <ul>
            <li>
              The Service is offered under paid subscription plans (Solo, Team,
              and Firm) billed monthly through Stripe.
            </li>
            <li>
              Features available depend on your subscription tier as described on
              our pricing page.
            </li>
            <li>
              You may cancel your subscription at any time. Cancellation takes
              effect at the end of the current billing period.
            </li>
            <li>
              We reserve the right to modify pricing with 30 days' notice.
              Continued use after a price change constitutes acceptance.
            </li>
            <li>
              Refunds are handled on a case-by-case basis. Contact support for
              refund requests.
            </li>
          </ul>
        </section>

        <section>
          <h2>5. Permitted Use</h2>
          <p>You agree to use the Service only for lawful purposes. You may not:</p>
          <ul>
            <li>
              Attempt to gain unauthorized access to other users' accounts or
              data
            </li>
            <li>
              Use the Service to violate any applicable law, regulation, or
              professional obligation
            </li>
            <li>
              Reverse engineer, decompile, or disassemble any part of the
              Service
            </li>
            <li>
              Use automated tools to scrape or extract data from the Service
              beyond normal use
            </li>
            <li>
              Resell, sublicense, or redistribute access to the Service without
              our written consent
            </li>
          </ul>
        </section>

        <section>
          <h2>6. Clio Integration</h2>
          <p>
            The Service accesses your Clio Manage account via read-only OAuth
            2.0 authorization. We do not modify, create, or delete any data in
            your Clio account. You may revoke access at any time through your
            Clio account settings. The availability and accuracy of data depends
            on Clio's API and your Clio account configuration.
          </p>
        </section>

        <section>
          <h2>7. Intellectual Property</h2>
          <p>
            The Service, including its design, features, and code, is owned by
            Case Raft and protected by copyright and intellectual property laws.
            Reports generated by the Service using your firm's data belong to
            you. You grant us no ownership rights over your Clio data.
          </p>
        </section>

        <section>
          <h2>8. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" and "as available" without
            warranties of any kind, whether express or implied. We do not
            guarantee that the Service will be uninterrupted, error-free, or
            meet your specific requirements. Reports are generated based on data
            from your Clio account and should be reviewed for accuracy before
            reliance.
          </p>
        </section>

        <section>
          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Case Raft shall not be
            liable for any indirect, incidental, special, consequential, or
            punitive damages arising from your use of the Service, including but
            not limited to loss of data, revenue, or business opportunities.
            Our total liability shall not exceed the amount you paid for the
            Service in the twelve months preceding the claim.
          </p>
        </section>

        <section>
          <h2>10. Confidentiality</h2>
          <p>
            We understand that law firm data is sensitive and may be subject to
            attorney-client privilege and other professional obligations. We
            treat all data accessed through Clio as confidential and do not
            share it with third parties except as described in our{" "}
            <Link to="/privacy-policy">Privacy Policy</Link>.
          </p>
        </section>

        <section>
          <h2>11. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service if you
            violate these Terms. You may terminate your account at any time by
            canceling your subscription and contacting support. Upon
            termination, your right to use the Service ceases and we will delete
            your account data within 30 days.
          </p>
        </section>

        <section>
          <h2>12. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify you of
            material changes by posting the updated terms on this page with a
            revised effective date. Continued use of the Service after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the
            laws of the State of Texas, without regard to conflict of law
            principles. Any disputes arising from these Terms or the Service
            shall be resolved in the courts located in Texas.
          </p>
        </section>

        <section>
          <h2>14. Contact Us</h2>
          <p>
            If you have questions about these Terms of Service, please contact
            us at{" "}
            <a href="mailto:support@caseraft.com">support@caseraft.com</a>.
          </p>
        </section>

        <div className="legal-footer">
          <p>&copy; {new Date().getFullYear()} Case Raft. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
