"""make case_id nullable for firm reports

Revision ID: af01d5e37348
Revises: 1094ca6f0d85
Create Date: 2026-03-09 20:12:29.957456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af01d5e37348'
down_revision = '1094ca6f0d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
